app = "govbot"
primary_region = "ewr"

[build]

[http_service]
  force_https = true
  internal_port = 3000
  auto_start_machines  = true
  auto_stop_machines   = "off"
  min_machines_running = 1
  processes            = ["app"]

[[http_service.ports]]
  port = 80
[[http_service.ports]]
  port = 443

[[http_service.checks]]
  grace_period   = "10s"
  interval       = "30s"
  timeout        = "5s"
  method         = "GET"
  path           = "/"
  headers        = {}

[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1